#!/usr/bin/env bash

SCRIPTS_DIR=/usr/bin/bastion
LOGIN_SCRIPT=${SCRIPTS_DIR}/shell
BASTION_LOG_DIR=/var/log/bastion
USER=ubuntu
GROUP=ubuntu

REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone | sed 's/[a-z]$//')
